spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3307/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka Client 와 통신할 Url을 지정한다.

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true # app health check
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 20s
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 20s
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
